version: "3.8"

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: geoalert-frontend:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes: []
